intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libtss2-headers%lib{tss2-headers}
import intf_libs += libtss2-sys%lib{tss2-sys}
import impl_libs += libtss2-mu%lib{tss2-mu}
import impl_libs += libtss2-tctildr%lib{tss2-tctildr}
import impl_libs += libcrypto%lib{crypto}

# Public headers.
#
pub = [dir_path] ../include/tss2/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{tss2-esys}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{tss2-esys}: {h c}{** -tss2-esys/esys_crypto_mbed} $impl_libs $intf_libs

# Build options.
#
# The sources include the public headers with unqualified names, so the
# tss2/ directory is also on the private header search path.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_unq = [dir_path] $out_root/include/tss2/
src_pfx_unq = [dir_path] $src_root/include/tss2/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc" \
              "-I$out_pfx_unq" "-I$src_pfx_unq"

c.poptions += -DLOG_FILE_ENABLED -DOSSL -DHAVE_EVP_SM3 -DHAVE_EVP_SM4_CFB \
              "-I$src_base/tss2-esys"

#obja{*}: c.poptions += -DTSS2_STATIC_BUILD
#objs{*}: c.poptions += -DTSS2_SHARED_BUILD

# Export options.
#
# The public headers include each other with unqualified names, so consumers
# also need the tss2/ directory on their header search path.
#
lib{tss2-esys}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                      "-I$out_pfx_unq" "-I$src_pfx_unq"
  c.export.libs = $intf_libs
}

lib{tss2-esys}: c.pkgconfig.include = include/ include/tss2/

#liba{tss2-esys}: c.export.poptions += -DTSS2_STATIC
#libs{tss2-esys}: c.export.poptions += -DTSS2_SHARED

# Only export the public API from the shared library on ELF targets.
#
lib{tss2-esys}: file{tss2-esys.map}: include = adhoc

if ($c.target.class == 'linux' || $c.target.class == 'bsd')
  libs{tss2-esys}: c.loptions += "-Wl,--version-script=$src_base/tss2-esys.map"

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
# A final release uses the same shared library names as upstream (libtool
# version-info 0:1:0): libtss2-esys.so.0.0.1 with SONAME libtss2-esys.so.0 on
# Linux, libtss2-esys.so.0 on BSD, and libtss2-esys.0.dylib on macOS. linux@
# needs MAJOR.MINOR[.EXTRA], macos@ and bsd@ are not implemented, so the
# BSD name is set through the extension.
#
if $version.pre_release
  lib{tss2-esys}: bin.lib.version = "-$version.project_id"
elif ($c.target.class == 'macos')
  lib{tss2-esys}: bin.lib.version = ".0"
elif ($c.target.class == 'bsd')
  libs{tss2-esys}: extension = "so.0"
else
  lib{tss2-esys}: bin.lib.version = "-0" linux@"0.0.1"

# Don't install private headers.
#
h{*}: install = false
